name: Build StampZ Linux (Ubuntu 18.04 Compatible)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux-ubuntu18:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build in Ubuntu 18.04 Docker container
      run: |
        docker run --rm -v "$PWD":/workspace -w /workspace ubuntu:18.04 bash -c "
          # Set timezone to avoid interactive prompts
          export DEBIAN_FRONTEND=noninteractive
          export TZ=UTC
          ln -snf /usr/share/zoneinfo/UTC /etc/localtime
          echo UTC > /etc/timezone
          
          # Update package lists
          apt-get update
          
          # Install Python 3.6 and development tools
          apt-get install -y python3 python3-pip python3-dev python3-tk tk-dev build-essential
          
          # Upgrade pip
          python3 -m pip install --upgrade pip
          
          # Install requirements
          pip3 install -r requirements.txt
          
          # Install PyInstaller
          pip3 install pyinstaller
          
          # Build using spec file
          python3 -m PyInstaller stampz.spec
          
          # Rename for Ubuntu 18.04 compatibility
          mv dist/StampZ dist/StampZ_linux-x64-ubuntu18
          
          # Show what was built
          echo 'Build completed. Contents:'
          ls -la dist/
          
          # Check GLIBC dependency
          echo 'GLIBC dependencies:'
          ldd dist/StampZ_linux-x64-ubuntu18 | grep libc || echo 'Static binary or no libc dependency shown'
        "
    
    - name: Upload Ubuntu 18.04 compatible executable
      uses: actions/upload-artifact@v4
      with:
        name: StampZ_linux-x64-ubuntu18
        path: dist/StampZ_linux-x64-ubuntu18
